In [3]:
import numpy as np

## Inicializar un arreglo de matrices de 3x3 con 3 elementos sin usar np.zeros(3,3,3)

In [21]:
respuesta=np.zeros(np.arange(27).reshape(3,3,3).shape)

In [22]:
respuesta

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## Generar un arreglo con la serie n^2, donde n empieza en 2 y termina en 8 en pasos de 2

In [40]:
arreglo=np.arange(2,8,2)**2

In [41]:
arreglo

array([ 4, 16, 36], dtype=int32)

## Generar un arreglo de matrices identidad con dimension respectiva a cada elemento del arreglo anterior

In [42]:
solucion = np.array([ np.eye(n) for n in arreglo])

In [43]:
solucion

array([array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]),
       array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [

## Demostrar que con el arreglo anterior se puede generar el arreglo: [4,16,36]

In [65]:
from functools import reduce
arreglo = np.array([reduce(lambda x,y:x,elemento.shape) for elemento in solucion])

In [66]:
arreglo

array([ 4, 16, 36])

## Suma de los n terminos donde n=100 (progresion artimetica)

In [69]:
np.arange(1,101).sum()

5050

## Demonstrar que np.sin([15,30,45,60,90]) = np.sin([165,150,135,120,90])

In [70]:
angulos_uno = np.array([15,30,45,60,90])* np.pi/180
angulos_dos  = np.array([165,150,135,120,90])* np.pi/180

In [82]:
np.sin(angulos_uno)

array([0.25881905, 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [83]:
np.sin(angulos_dos) 

array([0.25881905, 0.5       , 0.70710678, 0.8660254 , 1.        ])

## Eliminacion de numeros pares de una matriz

In [86]:
matriz = np.arange(1,26).reshape(5,5)

In [87]:
matriz

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [88]:
for i in np.nditer(matriz,order="F",op_flags=['readwrite']):
    if i%2==0:
        i[...] = 0

In [89]:
matriz

array([[ 1,  0,  3,  0,  5],
       [ 0,  7,  0,  9,  0],
       [11,  0, 13,  0, 15],
       [ 0, 17,  0, 19,  0],
       [21,  0, 23,  0, 25]])

## Demostrar que la matriz transpuesta de una matriz transpuesta es la matriz original