In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
arreglo_numeros = np.array([1,2,3])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.zeros(1,1)


TypeError: data type not understood

In [8]:
np.zeros(1,2)

TypeError: data type not understood

In [9]:
np.zeros((1,1))

array([[0.]])

In [10]:
np.zeros((4,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.empty((5))

array([1., 1., 1., 1., 1.])

In [14]:
np.empty((2,3,1))

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [15]:
print(np.empty((2,2,2)))

[[[0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000]]

 [[0.00000000e+000 7.21335843e-321]
  [1.11259940e-306 8.34443864e-308]]]


In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
print(np.eye(5,5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
np.arange(3)

array([0, 1, 2])

In [19]:
np.arange(1,23)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [20]:
print(np.arange(222,120))

[]


In [21]:
print(np.arange(112,120))

[112 113 114 115 116 117 118 119]


In [22]:
print(np.arange(4,20,2))

[ 4  6  8 10 12 14 16 18]


In [23]:
print(np.arange(4,20,2,1))

TypeError: data type not understood

In [24]:
print(np.arange(4,20,3))

[ 4  7 10 13 16 19]


In [25]:
np,array([(1,2,3),(4,5,6)])
         

NameError: name 'array' is not defined

In [26]:
np.array([(1,2,3),(4,5,6)])


array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arreglo_dimension=np.array([(1,2,3),(4,5,6)]).shape


In [28]:
print(arreglor_dimension)

NameError: name 'arreglor_dimension' is not defined

In [29]:
print(arreglo_dimension)

(2, 3)


In [30]:
np.arreglo(12).reshape(4,3)

AttributeError: module 'numpy' has no attribute 'arreglo'

In [34]:
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [35]:
np.ones_likes(np.arange(6).reshape(2,3))

AttributeError: module 'numpy' has no attribute 'ones_likes'

In [36]:
np.ones_like(np.arange(6).reshape(2,3))

array([[1, 1, 1],
       [1, 1, 1]])

In [38]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [39]:
np.arange(10000).reshape(1000,10)

array([[   0,    1,    2, ...,    7,    8,    9],
       [  10,   11,   12, ...,   17,   18,   19],
       [  20,   21,   22, ...,   27,   28,   29],
       ...,
       [9970, 9971, 9972, ..., 9977, 9978, 9979],
       [9980, 9981, 9982, ..., 9987, 9988, 9989],
       [9990, 9991, 9992, ..., 9997, 9998, 9999]])

In [40]:
a = np.array([10,10,10])

In [41]:
b = np.array([5,5,5])

In [42]:
print(a+b)

[15 15 15]


In [43]:
# Resta
print(a-b)

[5 5 5]


In [44]:
#Multiplicacion
print(a*b)

[50 50 50]


In [45]:
#Dvivision
print(a/b)

[2. 2. 2.]


In [48]:
arreglo_diez_ocho = np.arange(18)

In [50]:
print(arreglo_diez_ocho / 2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]


In [51]:
# Expresiones
print(arreglo_diez_ocho > 9)

[False False False False False False False False False False  True  True
  True  True  True  True  True  True]


In [52]:
# Multiplicacion de varias dimensiones
A = np.arange(4).reshape(2,2)
B = np.arange(4,6).reshape(2,2)

ValueError: cannot reshape array of size 2 into shape (2,2)

In [53]:
B = np.arange(4,7).reshape(2,2)

ValueError: cannot reshape array of size 3 into shape (2,2)

In [54]:
B = np.arange(4,8).reshape(2,2)

In [56]:
print(A,B)

[[0 1]
 [2 3]] [[4 5]
 [6 7]]


In [57]:
print(A*B)

[[ 0  5]
 [12 21]]


In [58]:
A > B

array([[False, False],
       [False, False]])

In [59]:
# Multiplicacion dot

In [61]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [62]:
np.dot(B,A)

array([[10, 19],
       [14, 27]])

In [63]:
# Operaciones conocidas en los arreglos
arreglo_diez_elementos = np.arange(10)
print(arreglo_diez_elementos.sum())
print(arreglo_diez_elementos.min())
print(arreglo_diez_elementos.max())

45
0
9


In [64]:
arreglo_tres_cuatro = np.arange(12).reshape(3,4)

In [65]:
print(arreglo_tres_cuatro.sum(axis=0))# X

[12 15 18 21]


In [67]:
print(arreglo_tres_cuatro.sum(axis=1))# Y

[ 6 22 38]


In [68]:
#h1 Universal Functions

In [69]:
angulos_cero_noventa = np.array([0,30,45,60,90])
print(angulos_cero_noventa)

[ 0 30 45 60 90]


In [70]:
angulos_cero_noventa_radianes = angulos_cero_noventa * np*pi / 180


TypeError: unsupported operand type(s) for *: 'int' and 'module'

In [73]:
angulos_cero_noventa_radianes = angulos_cero_noventa * np.pi/180


In [74]:
print (angulos_cero_noventa_radianes)

[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [75]:
# Funcion seno
print(np.cos(angulos_cero_noventa))

[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]


In [76]:
np.cos(30)

0.15425144988758405

In [78]:
np.sin(30)

-0.9880316240928618

In [89]:
arreglo_diez = np.random.rand(30)*10

In [90]:
print(arreglo_diez)
print(np.mean(arreglo_diez)) # Media

[8.55712234 2.43791591 7.87115523 8.16426463 6.95092021 3.57333911
 1.65307006 1.00248553 1.63484401 7.32401639 5.1530628  0.92984621
 3.55330313 0.77607279 8.23404327 3.73917045 9.94741675 2.03037255
 9.84433126 1.23400001 6.44065578 6.69825867 6.50470275 6.99647018
 5.06928621 8.35811005 1.40811177 9.62456543 5.29366999 4.06591392]
5.16901657979106


In [91]:
print(np.median(arreglo_diez))

5.223366394638673


In [92]:
# Desviacion Estandar
print(arreglo_diez)
print(np.std(arreglo_diez))

[8.55712234 2.43791591 7.87115523 8.16426463 6.95092021 3.57333911
 1.65307006 1.00248553 1.63484401 7.32401639 5.1530628  0.92984621
 3.55330313 0.77607279 8.23404327 3.73917045 9.94741675 2.03037255
 9.84433126 1.23400001 6.44065578 6.69825867 6.50470275 6.99647018
 5.06928621 8.35811005 1.40811177 9.62456543 5.29366999 4.06591392]
2.9643570637613976


In [93]:
# Varianza
print(arreglo_diez)
print(np.var(arreglo_diez))

[8.55712234 2.43791591 7.87115523 8.16426463 6.95092021 3.57333911
 1.65307006 1.00248553 1.63484401 7.32401639 5.1530628  0.92984621
 3.55330313 0.77607279 8.23404327 3.73917045 9.94741675 2.03037255
 9.84433126 1.23400001 6.44065578 6.69825867 6.50470275 6.99647018
 5.06928621 8.35811005 1.40811177 9.62456543 5.29366999 4.06591392]
8.787412801472096


In [96]:
# Salarios
salarios = np.genfromtxt('data/salarios.csv',delimiter=',')

In [99]:
print(salarios)
print(salarios.shape)

[[ 1.  2. 12. 13. 15.  6.  7.  8. 12. 15. 19. 12. 20.]
 [ 1.  2. 12. 13. 15.  6.  7.  8. 12. 15. 19. 12. 20.]
 [ 1.  2. 12. 13. 15.  6.  7.  8. 12. 15. 19. 12. 20.]
 [ 1.  2. 12. 13. 15.  6.  7.  8. 12. 15. 19. 12. 20.]
 [ 1.  2. 12. 13. 15.  6.  7.  8. 12. 15. 19. 12. 20.]
 [ 1.  2. 12. 13. 15.  6.  7.  8. 12. 15. 19. 12. 20.]
 [ 1.  2. 12. 13. 15.  6.  7.  8. 12. 15. 19. 12. 20.]]
(7, 13)


In [114]:
# Slice and Dice
arreglo_once_cuadrado = np.arange(11)**2
print(arreglo_once_cuadrado)
print(arreglo_once_cuadrado[0])
print(arreglo_once_cuadrado[-8:-1])
print(arreglo_once_cuadrado[1:])
print(arreglo_once_cuadrado[2:8:4]) # en pasos de 4
print(arreglo_once_cuadrado[::-1]) # recorrer al reves


[  0   1   4   9  16  25  36  49  64  81 100]
0
[ 9 16 25 36 49 64 81]
[  1   4   9  16  25  36  49  64  81 100]
[ 4 36]
[100  81  64  49  36  25  16   9   4   1   0]
