In [2]:
import numpy as np

In [3]:
arreglo_diez_seis = np.arange(16).reshape(4,4)

In [4]:
arreglo_diez_seis

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
indice_boolenano_mayores_a_ocho = arreglo_diez_seis > 8
indice_boolenano_mayores_a_ocho

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [6]:
print(arreglo_diez_seis[indice_boolenano_mayores_a_ocho])

[ 9 10 11 12 13 14 15]


In [7]:
print(np.count_nonzero(indice_boolenano_mayores_a_ocho)) # Numero de elementos que cumplen la condicion

7


In [9]:
print(np.sum(indice_boolenano_mayores_a_ocho,axis=1))

[0 0 3 4]


In [10]:
print(np.any(indice_boolenano_mayores_a_ocho)) # Alguno que cumple la condicion

True


In [12]:
indice_boolenano_mayores_a_veinte = arreglo_diez_seis > 20

In [13]:
print(np.all(indice_boolenano_mayores_a_veinte)) 

False


In [15]:
print(np.all(indice_boolenano_mayores_a_ocho,axis=1)) 

[False False False  True]
