In [5]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([10,10,10,10,10])
print(a*b)

[10 20 30 40 50]


In [6]:
d = np.ones((4,3))

In [7]:
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
alturas = [1.60,1.65,1.80] #Metros
pesos = [165,170,185]

In [10]:
datos_estudiantes = np.array([alturas,pesos])

In [11]:
transformacion = np.array([100,2.2])

In [12]:
transformacion.shape

(2,)

In [13]:
datos_estudiantes * transformacion

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [15]:
transformacion_1 = np.array([[100],[2.2]])

In [16]:
transformacion_1

array([[100. ],
       [  2.2]])

In [17]:
datos_estudiantes * transformacion_1

array([[160., 165., 180.],
       [363., 374., 407.]])