## Crear un vector de ceros de tamaño 10

In [13]:
import numpy as np
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1

In [4]:
vector = np.zeros(10)
vector[5]=1
print(vector)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


## Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc

In [6]:
vector = np.arange(50)
aux=vector[0]
aux2=vector[-1]
vector[-1]=aux
vector[0]=aux2
print(vector)

[49  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48  0]


## Crear una matriz de 3 x 3 con valores del cero al 8

In [9]:
vector = np.arange(9).reshape(3,3)
print(vector)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Encontrar los indices que no sean cero en un arreglo

In [1]:
import numpy as np
arreglo = [1,2,0,0,4,0]
arreglo_n = np.array([1,2,0,0,4,0])
indices_arreglo_no_cero = arreglo_n > 0
print(arreglo_n[indices_arreglo_no_cero])
print(indices_arreglo_no_cero)

[1 2 4]
[ True  True False False  True False]


## Crear una matriz de identidad 3 x 3 

In [17]:
matriz = np.eye(3)
print(matriz)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Crear una matriz 3 x 3 x 3 con valores randomicos

In [24]:
matriz = np.random.rand(3,3,3)
print(matriz)

[[[0.71841238 0.6867064  0.58858865]
  [0.3736167  0.77645038 0.07940413]
  [0.46531386 0.66861176 0.13249637]]

 [[0.85675386 0.98574113 0.77994598]
  [0.22140529 0.78280038 0.51387706]
  [0.36631051 0.23445799 0.70863656]]

 [[0.74774425 0.04706732 0.98164184]
  [0.20144488 0.91214353 0.0274571 ]
  [0.68585269 0.76855559 0.0695637 ]]]


## Crear una matriz 10 x 10 y encontrar el mayor y el menor

In [35]:
matriz = np.arange(100).reshape(10,10)
print("Mayor valor ",matriz.max())
print("Menor valor ",matriz.min())

Mayor valor  99
Menor valor  0


## Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)

In [20]:
from scipy import misc
mapache = misc.face()
unicos_elementos = np.unique(mapache)
print(unicos_elementos.size)

a = np.unique(mapache.reshape(-1, mapache.shape[2]), axis=0)
print(a[256])

256
[ 5 11 11]


## ¿Como crear una serie de una lista, diccionario o arreglo?

In [41]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [3]:
import pandas as pd 
serie_lista = pd.Series(mylist)
print(serie_lista)

NameError: name 'mylist' is not defined

In [44]:
serie_dict = pd.Series(mydict)
print(serie_dict)

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


## ¿Como convertir el indice de una serie en una columna de un DataFrame?

In [5]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 

In [6]:
datos =pd.DataFrame()
datos.append(ser,ignore_index=True)

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
df = ser.to_frame().reset_index()
print(df.head())


  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


## ¿Como combinar varias series para hacer un DataFrame?

In [65]:
import numpy as np
datos =pd.DataFrame()
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
datos=datos.append(ser1,ignore_index=True)
datos=datos.append(ser2,ignore_index=True)
print(datos)

  0  1  2  3  4  5  6  7  8  9  ...  16  17  18  19  20  21  22  23  24  25
0  a  b  c  e  d  f  g  h  i  j ...   q   r   s   t   u   v   w   x   y   z
1  0  1  2  3  4  5  6  7  8  9 ...  16  17  18  19  20  21  22  23  24  25

[2 rows x 26 columns]


## ¿Como obtener los items que esten en una serie A y no en una serie B?

In [66]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [108]:
indices= ser1.isin(ser2)
ser1[np.invert(indices)]

0    1
1    2
2    3
dtype: int64

## ¿Como obtener los items que no son comunes en una serie A y serie B?

In [88]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [109]:
indices= ser1.isin(ser2)
ser1[np.invert(indices)]
indices2= ser2.isin(ser1)
ser2[np.invert(indices2)]
print(ser1[np.invert(indices)],ser2[np.invert(indices2)])

0    1
1    2
2    3
dtype: int64 2    6
3    7
4    8
dtype: int64


1    5
2    6
3    7
4    8
dtype: int64

## ¿Como obtener el numero de veces que se repite un valor en una serie?

In [110]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

In [112]:
ser.value_counts()

a    5
c    5
g    4
e    4
h    4
d    4
f    3
b    1
dtype: int64

## ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?

In [113]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

In [117]:
ser.fillna(0)

0     1
1     4
2     1
3     4
4     3
5     4
6     4
7     2
8     3
9     1
10    2
11    4
dtype: int32

## ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un `shape` definido?

In [123]:
ser = pd.Series(np.random.randint(1, 10, 35))
datos = pd.DataFrame()
datos.append(ser,ignore_index=True)

0    1    2    3    4    5    6    7    8    9  ...    25   26   27   28  \
0  6.0  9.0  5.0  7.0  1.0  4.0  5.0  7.0  8.0  3.0 ...   7.0  8.0  5.0  9.0   

    29   30   31   32   33   34  
0  8.0  4.0  2.0  9.0  3.0  7.0  

[1 rows x 35 columns]

In [119]:
ser

0     1
1     4
2     4
3     6
4     3
5     1
6     3
7     2
8     8
9     8
10    9
11    3
12    7
13    3
14    3
15    5
16    5
17    2
18    4
19    4
20    3
21    4
22    6
23    4
24    2
25    7
26    4
27    7
28    2
29    9
30    5
31    3
32    7
33    8
34    1
dtype: int32

## ¿Obtener los valores de una serie conociendo la posicion por indice?

In [124]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

In [125]:
ser.iloc[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

## ¿Como anadir series vertical u horizontalmente a un DataFrame?


In [126]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [127]:
# horizontalmente
datos = pd.DataFrame()

In [133]:
datos.append(ser1,ignore_index=True)

0    1    2    3    4
0  0.0  1.0  2.0  3.0  4.0

## ¿Obtener la media de una serie agrupada por otra serie?

In [134]:
frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['manzana', 'zanahoria', 'manzana', 'manzana', 'banana', 'manzana', 'banana', 'manzana', 'zanahoria', 'manzana']


## ¿Como importar solo columnas especificas de un archivo csv?

In [138]:
url = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'
datos = pd.read_csv(url)
columnas = ["crim","zn","indus","chas"]

In [139]:
datos = datos[columnas]

In [140]:
datos

crim    zn  indus  chas
0     0.00632  18.0   2.31     0
1     0.02731   0.0   7.07     0
2     0.02729   0.0   7.07     0
3     0.03237   0.0   2.18     0
4     0.06905   0.0   2.18     0
5     0.02985   0.0   2.18     0
6     0.08829  12.5   7.87     0
7     0.14455  12.5   7.87     0
8     0.21124  12.5   7.87     0
9     0.17004  12.5   7.87     0
10    0.22489  12.5   7.87     0
11    0.11747  12.5   7.87     0
12    0.09378  12.5   7.87     0
13    0.62976   0.0   8.14     0
14    0.63796   0.0   8.14     0
15    0.62739   0.0   8.14     0
16    1.05393   0.0   8.14     0
17    0.78420   0.0   8.14     0
18    0.80271   0.0   8.14     0
19    0.72580   0.0   8.14     0
20    1.25179   0.0   8.14     0
21    0.85204   0.0   8.14     0
22    1.23247   0.0   8.14     0
23    0.98843   0.0   8.14     0
24    0.75026   0.0   8.14     0
25    0.84054   0.0   8.14     0
26    0.67191   0.0   8.14     0
27    0.95577   0.0   8.14     0
28    0.77299   0.0   8.14     0
29    1.00245   0.0   8.14     0
..        ...   ...    ...   ...
476   4.87141   0.0  18.10     0
477  15.02340   0.0  18.10     0
478  10.23300   0.0  18.10     0
479  14.33370   0.0  18.10     0
480   5.82401   0.0  18.10     0
481   5.70818   0.0  18.10     0
482   5.73116   0.0  18.10     0
483   2.81838   0.0  18.10     0
484   2.37857   0.0  18.10     0
485   3.67367   0.0  18.10     0
486   5.69175   0.0  18.10     0
487   4.83567   0.0  18.10     0
488   0.15086   0.0  27.74     0
489   0.18337   0.0  27.74     0
490   0.20746   0.0  27.74     0
491   0.10574   0.0  27.74     0
492   0.11132   0.0  27.74     0
493   0.17331   0.0   9.69     0
494   0.27957   0.0   9.69     0
495   0.17899   0.0   9.69     0
496   0.28960   0.0   9.69     0
497   0.26838   0.0   9.69     0
498   0.23912   0.0   9.69     0
499   0.17783   0.0   9.69     0
500   0.22438   0.0   9.69     0
501   0.06263   0.0  11.93     0
502   0.04527   0.0  11.93     0
503   0.06076   0.0  11.93     0
504   0.10959   0.0  11.93     0
505   0.04741   0.0  11.93     0

[506 rows x 4 columns]